#!/usr/bin/env python3

import argparse
import json
from pathlib import Path
from datetime import datetime

import xlsxwriter

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate an Excel workbook with data + embedded pie chart.")
    parser.add_argument("--payload", required=True, help="Path to payload JSON generated by send-chart-request.ts")
    return parser.parse_args()

def load_payload(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)

def main() -> None:
    args = parse_args()
    payload = load_payload(Path(args.payload))

    output_path = Path(payload["outputPath"])
    _template_path = Path(payload.get("templatePath", ""))
    sheet_name = payload.get("sheetName") or "Data"
    headers = payload.get("headers") or []
    rows = payload.get("rows") or []

    output_path.parent.mkdir(parents=True, exist_ok=True)
    workbook = xlsxwriter.Workbook(output_path.as_posix())
    data_ws = workbook.add_worksheet(sheet_name)
    meta_ws = workbook.add_worksheet("TemplateMeta")

    header_fmt = workbook.add_format({"bold": True, "font_color": "#FFFFFF", "bg_color": "#184F3F"})

    for col, h in enumerate(headers):
        data_ws.write(0, col, h, header_fmt)

    for r, row in enumerate(rows, start=1):
        for c, h in enumerate(headers):
            value = row.get(h)
            if isinstance(value, (int, float)):
                data_ws.write_number(r, c, value)
            else:
                data_ws.write(r, c, value)

    data_ws.set_column("A:A", 18)
    data_ws.set_column("B:B", 14)

    # Dynamically set chart range to actual data
    if rows:
        max_data_row = len(rows)
    else:
        max_data_row = 1
    chart = workbook.add_chart({"type": "pie"})
    chart.add_series({
        "name": "Pie Data",
        "categories": [sheet_name, 1, 0, max_data_row, 0],
        "values": [sheet_name, 1, 1, max_data_row, 1],
    })
    chart.set_title({"name": "Pie Chart Template (Edit Data sheet to update)"})
    chart.set_legend({"position": "right"})
    chart.set_size({"width": 600, "height": 420})
    data_ws.insert_chart("D2", chart)

    meta_ws.write("A1", "Template purpose")
    meta_ws.write("B1", "Editable pie chart export with embedded chart")
    meta_ws.write("A2", "Required columns")
    meta_ws.write("B2", "A=label, B=value")
    meta_ws.write("A3", "How to use")
    meta_ws.write("B3", "Replace or append rows in Data sheet; chart updates automatically.")
    meta_ws.write("A4", "Generator")
    meta_ws.write("B4", "scripts/fill_excel_template_pie.py")
    meta_ws.set_column("A:A", 20)
    meta_ws.set_column("B:B", 72)

    workbook.close()
    print(f"Template workbook generated: {output_path}")

if __name__ == "__main__":
    main()
